FROM ubuntu:22.04

RUN apt update && apt upgrade -y && \
    apt install mc python3-pip -y && \
    pip3 install jupyter


ENV user="vbalab"

RUN useradd -m -d /home/${user} ${user} && \
    chown -R ${user}:${user} /home/${user} && \
    chmod 700 /home/${user}

ADD ./start.sh /home/${user}/start.sh
RUN chown ${user} /home/${user}/start.sh
RUN chmod u+x /home/${user}/start.sh

USER ${user}
WORKDIR /home/${user}

ENTRYPOINT ["/home/vbalab/start.sh"]
